### ISSUE TITLE
remove dat1

### ISSUE THREAD

**Issue by gogolok** [phartz/service-broker-cli#3]
The file ```dat1``` in the root folder should be part of the project, correct?
It gets written by ```tests/commandline_test.go```, doesn't get cleaned up and is not on gitignore.

**Comment by phartz** [comment]
thx for this hint, I removed the file and added it to gitignore

I'll don't close the issue, I'll change the tests to use a temp folder

**Comment by gogolok** [comment]
👍

**Comment by phartz** [comment]
fixed within this this [commit](https://github.com/phartz/service-broker-cli/commit/39c87a7f0f17629002af0d2e2274a88514f60107)
